export const animeList = [
    { name: "Shingeki no Kyojin", type: "series" },
    { name: "Naruto", type: "series" },
    { name: "Kimetsu no Yaiba", type: "series" },
    { name: "Fullmetal Alchemist Brotherhood", type: "series" },
    { name: "Naruto Shippuden", type: "series" },
    { name: "Shigatsu wa Kimi no Uso", type: "series" },
    { name: "Anohana", type: "series" },
    { name: "Dragon Ball", type: "series" },
    { name: "Dragon Ball Z", type: "series" },
    { name: "Dragon Ball Super", type: "series" },
    { name: "Tokyo Ghoul", type: "series" },
    { name: "Nanatsu no Taizai", type: "series" },
    { name: "Fairy Tail", type: "series" },
    { name: "Sukitte Ii na yo", type: "series" },
    { name: "Sword Art Online", type: "series" },
    { name: "Sword Art Online II", type: "series" },
    { name: "No Game No Life", type: "series" },
    { name: "Dragon Ball GT", type: "series" },
    { name: "Cyberpunk Edgerunners", type: "series" },
    { name: "Kimetsu no Yaiba Yuukaku-hen", type: "series" },
    { name: "Death Note", type: "series" },
    { name: "Oshi no Ko", type: "series" },
    { name: "Boruto Naruto next generation", type: "series" },
    { name: "Salaryman ga Isekai ni Ittara Shitenno ni Natta Hanashi", type: "series" },
    { name: "Botsuraku Yotei no Kizoku dakedo Hima Datta kara Mahou wo Kiwamete mita", type: "series" },
    { name: "Mahoutsukai no Yakusoku", type: "series" },
    { name: "Kuroiwa Medaka ni Watashi no Kawaii ga Tsuujinai", type: "series" },
    { name: "Kono Kaisha ni Suki na Hito ga Imasu", type: "series" },
    { name: "Hana wa Saku Shura no Gotok", type: "series" },
    { name: "Hazure Skill Kinomi Master Skill no Mi Tabetara Shinu wo Mugen ni Taberareru You ni Natta Ken Nitsuite", type: "series" },
    { name: "Magic Maker Isekai Mahou no Tsukurikata", type: "series" },
    { name: "Ameku Takao no Suiri Karte", type: "series" },
    { name: "Honey Lemon Soda", type: "series" },
    { name: "Izure Saikyou no Renkinjutsushi", type: "series" },
    { name: "Sousei no Aquarion Myth of Emotions", type: "series" },
    { name: "Momentary Lily", type: "series" },
    { name: "Fuguushoku Kanteishi ga Jitsu wa Saikyou Datta Naraku de Kitaeta Saikyou no Shingan de Musou Suru", type: "series" },
    { name: "Douse Koishite Shimaunda", type: "series" },
    { name: "Around 40 Otoko no Isekai Tsuuhan", type: "series" },
    { name: "Akuyaku Reijou Tensei Oji-san", type: "series" },
    { name: "Class no Daikirai na Joshi to Kekkon Suru Koto ni Natta", type: "series" },
    { name: "Girumasu", type: "series" },
    { name: "Nihon e Youkoso Elf-san", type: "series" },
    { name: "Tasokare Hotel", type: "series" },
    { name: "Ubel Blatt", type: "series" },
    { name: "Sorairo Utility TV", type: "series" },
    { name: "Farmagia", type: "series" },
    { name: "Baban Baban Ban Vampire", type: "series" },
    { name: "Sakamoto Days", type: "series" },
    { name: "S-Rank Monster no Behemoth Dakedo Neko to Machigawarete Elf Musume no Pet to Shite Kurashitemasu", type: "series" },
    { name: "Okinawa de Suki ni Natta Ko ga Hougen Sugite Tsura Sugiru", type: "series" },
    { name: "NEET Kunoichi to Naze ka Dousei Hajimemashita", type: "series" },
    { name: "Medalist", type: "series" },
    { name: "A-Rank Party wo Ridatsu Shita Ore wa Moto Oshiegotachi to Meikyuu Shinbu wo Mezasu", type: "series" },
    { name: "Sentai Red Isekai de Boukensha ni Naru", type: "series" },
    { name: "Zenshuu", type: "series" },
    { name: "Kisaki Kyouiku kara Nigetai Watashi", type: "series" },
    { name: "Kimetsu no Yaiba Hashira Geiko-hen", type: "series" },
    { name: "Shichisei no Subaru", type: "series" },
    { name: "Captain Tsubasa 2018", type: "series" },
    { name: "Wotaku ni Koi wa Muzukashii", type: "series" },
    { name: "Nanatsu no Taizai Imashime no Fukkatsu", type: "series" },
    { name: "Nanatsu no Taizai Kamigami no Gekirin", type: "series" },
    { name: "Nanatsu no Taizai Seisen no Shirushi", type: "series" },
    { name: "Nanatsu no Taizai Fundo no Shinpan", type: "series" },
    { name: "Saenai Heroine no Sodatekata ♭", type: "series" },
    { name: "Saenai Heroine no Sodatekata", type: "series" },
    { name: "Shingeki no Kyojin Season 2", type: "series" },
    { name: "Shingeki no Kyojin Season 3", type: "series" },
    { name: "Shingeki no Kyojin Season 3 Part 2", type: "series" },
    { name: "Masamune-kun no Revenge", type: "series" },
    { name: "Runway de Waratte", type: "series" },
    { name: "Araburu Kisetsu no Otome-domo yo", type: "series" },
    { name: "Dr Stone", type: "series" },
    { name: "Dr Stone Stone Wars", type: "series" },
    { name: "ToraDora", type: "series" },
    { name: "Dr Stone Ryuusui", type: "series" },
    { name: "Dr Stone New World", type: "series" },
    { name: "Domestic na Kanojo", type: "series" },
    { name: "Kanokon", type: "series" },
    { name: "AkaneIro ni Somaru Saka", type: "series" },
    { name: "Seishun Buta Yarou wa Bunny Girl Senpai no Yume wo Minai", type: "series" },
    { name: "Baka to Test to Shoukanjuu", type: "series" },
    { name: "High Score Girl", type: "series" },
    { name: "High Score Girl II", type: "series" },
    { name: "Angel Beats", type: "series" },
    { name: "Yesterday wo Utatte", type: "series" },
    { name: "Death Parade", type: "series" },
    { name: "Baka to Test to Shokanju Ni", type: "series" },
    { name: "Zero no Tsukaima Final", type: "series" },
    { name: "B Gata H Kei", type: "series" },
    { name: "Zero no Tsukaima Princess no Rondo", type: "series" },
    { name: "Zero no Tsukaima Futatsuki no Kishi", type: "series" },
    { name: "Kaichou wa maid sama", type: "series" },
    { name: "Zero no Tsukaima", type: "series" },
    { name: "Ishuzoku Reviewers", type: "series" },
    { name: "Sakurasou no Pet na Kanojo", type: "series" },
    { name: "Shinmai Maou no Testament Burst", type: "series" },
    { name: "Another", type: "series" },
    { name: "Boku wa Tomodachi ga Sukunai", type: "series" },
    { name: "Tokyo Ghoul A", type: "series" },
    { name: "Ano Natsu de Matteru", type: "series" },
    { name: "Ore no Kanojo to Osananajimi ga Shuraba Sugiru", type: "series" },
    { name: "Shingeki no Kyojin The Final Season", type: "series" },
    { name: "Nazo no Kanojo X", type: "series" },
    { name: "Shingeki no Kyojin The Final Season Part 2", type: "series" },
    { name: "Hunter x Hunter 2011", type: "series" },
    { name: "Nagi no Asukara", type: "series" },
    { name: "Tonari no Kaibutsu-kun", type: "series" },
    { name: "Kamisama ni Natta Hi", type: "series" },
    { name: "Hentai Ouji to Warawanai Neko", type: "series" },
    { name: "K", type: "series" },
    { name: "Absolute Duo", type: "series" },
    { name: "Boku wa Tomodachi ga Sukunai NEXT", type: "series" },
    { name: "Shinmai Maou no Testament", type: "series" },
    { name: "Mondaiji-tachi ga Isekai kara Kuru Sou Desu yo", type: "series" },
    { name: "Oregairu", type: "series" },
    { name: "Rakudai Kishi no Cavalry", type: "series" },
    { name: "Isuca", type: "series" },
    { name: "Plastic Memories", type: "series" },
    { name: "Golden Time", type: "series" },
    { name: "Yahari Ore no Seishun Love Comedy wa Machigatteiru Zoku", type: "series" },
    { name: "Chuunibyou demo Koi ga Shitai", type: "series" },
    { name: "Inari Konkon Koi Iroha", type: "series" },
    { name: "Gakusen Toshi Asterisk 2nd Season", type: "series" },
    { name: "Akame ga Kill", type: "series" },
    { name: "Charlotte", type: "series" },
    { name: "Yamada-kun to 7-nin no Majo", type: "series" },
    { name: "Kanojo to Kanojo no Neko Everything Flows", type: "series" },
    { name: "Tokyo Revengers", type: "series" },
    { name: "Gift Eternal Rainbow", type: "series" },
    { name: "Boku dake ga Inai Machi", type: "series" },
    { name: "Horimiya", type: "series" },
    { name: "Watashi no Shiawase na Kekkon", type: "series" },
    { name: "Gakusen Toshi Asterisk", type: "series" },
    { name: "Kimetsu no Yaiba Katanakaji no Sato-hen", type: "series" },
    { name: "Lovely Complex", type: "series" },
    { name: "Lamune", type: "series" },
    { name: "Kimi no na wa", type: "movies" },
    { name: "Boruto Naruto the movie", type: "movies" },
    { name: "Koe no Katachi", type: "movies" },
    { name: "Kimetsu no Yaiba Movie Mugen Ressha-hen", type: "movies" },
    { name: "Kimi no suizou wo tabetai", type: "movies" },
    { name: "Boku ga Aishita Subete no Kimi e", type: "movies" },
    { name: "Sword Art Online Progressive Movie - Hoshi Naki Yoru no Aria", type: "movies" },
    // aca cambiar
    { name: "Black Fox", type: "movies" },
    { name: "Tenki no Ko", type: "movies" },
    { name: "Seishun Buta Yarou wa Yumemiru Shoujo no Yume wo Minai", type: "movies" },
    { name: "Kimi to Nami ni Noretara", type: "movies" },
    { name: "Nanatsu no Taizai Movie Tenkuu no Torawarebito", type: "movies" },
    { name: "Shikioriori", type: "movies" },
    { name: "Uchiage Hanabi, Shita kara Miru ka Yoko kara Miru ka", type: "movies" },
    { name: "Suki ni Naru Sono Shunkan wo", type: "movies" },
    { name: "Sword Art Online Movie Ordinal Scale", type: "movies" },
    { name: "Zutto Mae kara Suki deshita. Kokuhaku Jikkou Iinkai", type: "movies" },
    { name: "Kokoro ga Sakebitagatterunda.", type: "movies" },
    { name: "Naruto Shippuuden Movie 7 - The Last", type: "movies" },
    { name: "Omoide no Marnie", type: "movies" },
    { name: "Hunter x Hunter The Last Mission", type: "movies" },
    { name: "Sakasama no Patema", type: "movies" },
    { name: "Kaze Tachinu", type: "movies" },
    { name: "Hal", type: "movies" },
    { name: "Kotonoha no Niwa", type: "movies" },
    { name: "Dragon Ball Z Battle of Gods", type: "movies" },
    { name: "Hunter x Hunter Phantom Rouge", type: "movies" },
    { name: "Nerawareta Gakuen", type: "movies" },
    { name: "Ookami Kodomo no Ame to Yuki", type: "movies" },
    { name: "Naruto Shippuden Blood Prison", type: "movies" },
    { name: "Viaje a agartha", type: "movies" },
    { name: "Summer Wars", type: "movies" },
    { name: "Akira", type: "movies" },
    { name: "Hotaru no Haka", type: "movies" },
    { name: "Hotarubi no Mori e", type: "movies" },
    { name: "Kumo No Mukou Yakusoku No Basho", type: "movies" },
    { name: "Suzume", type: "movies" },
    { name: "Belle", type: "movies" },
    { name: "Mirai no Mirai", type: "movies" },
    { name: "Bakemono no Ko", type: "movies" },
    { name: "Naruto Shippuden The Movie", type: "movies" }, // ver
    { name: "Byousoku 5 Centimeter", type: "movies" },
    { name: "Toki wo Kakeru Shoujo", type: "movies" },
    { name: "El niño y la garza", type: "movies" },
    { name: "Sora no Aosa wo Shiru Hito yo", type: "movies" },
    { name: "Seishun Buta Yarou wa Randoseru Girl no Yume wo Minai", type: "movies" },
    { name: "Chiisana Eiyuu Kani to Tamago to Toumei Ningen", type: "movies" },
    { name: "Seishun Buta Yarou wa Odekake Sister no Yume wo Minai", type: "movies" },
    { name: "Liz to Aoi Tori", type: "movies" },
    { name: "Cencoroll Connect", type: "movies" },
    { name: "Big Fish & Begonia", type: "movies" },
    { name: "Kimi no Koe wo Todoketai", type: "movies" },
    { name: "El Cuento de la Princesa Kaguya", type: "movies" },
    { name: "Hakubo", type: "movies" },
    { name: "Nakitai Watashi wa Neko wo Kaburu", type: "movies" },
    { name: "Dragon Ball Super Broly", type: "movies" },
    { name: "Dragon Ball Z La Resurrección de Freezer", type: "movies" },
    { name: "Dragon Ball GT 100 Años Después", type: "movies" },
    { name: "Dragon Ball Z Pelicula 13 El ataque del dragón", type: "movies" },
    { name: "Dragon Ball Z Pelicula 12 La fusión de Goku y Vegeta", type: "movies" },
    { name: "Dragon Ball Z Pelicula 11 El combate final", type: "movies" },
    { name: "Dragon Ball Z Pelicula 10 El regreso del Guerrero Legendario", type: "movies" },
    { name: "Dragon Ball Z Pelicula 09 La Galaxia corre peligro", type: "movies" },
    { name: "Dragon Ball Z Pelicula 08 El poder invencible", type: "movies" },
    { name: "Dragon Ball Z Pelicula 07 La pelea de los tres Saiyajin", type: "movies" },
    { name: "Dragon Ball Z Pelicula 06 El regreso de Cooler", type: "movies" },
    { name: "Dragon Ball Z Pelicula 05 Los rivales mas poderosos", type: "movies" },
    { name: "Dragon Ball Z Pelicula 04 Goku es un Super Saiyajin", type: "movies" },
    { name: "Dragon Ball Z Pelicula 03 La batalla más grande del mundo esta por comenzar", type: "movies" },
    { name: "Dragon Ball Z Pelicula 02 El hombre más fuerte de este mundo", type: "movies" },
    { name: "Dragon Ball Z Pelicula 01 Devuelveme a mi Gohan", type: "movies" },

];